export type MiniAayushPose =
  | '01-greet'
  | '02-think'
  | '03-work'
  | '04-idea'
  | '05-walk'
  | '06-fall'
  | '07-getup'
  | '08-chill'
  | '09-peek'
  | '10-celebrate'
  | '11-confused'
  | '12-sleep'
  | '13-carry'
  | '14-guide'
  | '15-type'
  | '16-bye'
  | 'hero_standing'

export type MiniAayushMood =
  | 'idle'
  | 'walking'
  | 'stumbling'
  | 'fallen'
  | 'recovering'
  | 'thinking'
  | 'working'
  | 'guiding'
  | 'sleeping'
  | 'celebrating'
